// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvm427-CUTP4N8N-vkWV1BO3Cxp5JXgQ0',
    appId: '1:1024772684219:web:01ea2fc5e3fbb6b0386c9e',
    messagingSenderId: '1024772684219',
    projectId: 'community-56642',
    authDomain: 'community-56642.firebaseapp.com',
    storageBucket: 'community-56642.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA674IABkVKmKukzlcyEKyi16Fk4i6p4bk',
    appId: '1:1024772684219:android:e00dd2b15dea09fd386c9e',
    messagingSenderId: '1024772684219',
    projectId: 'community-56642',
    storageBucket: 'community-56642.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZBGyfumJ-qTbyiJ1R0r9Tl38nfdEX8ww',
    appId: '1:1024772684219:ios:1258d139ba770637386c9e',
    messagingSenderId: '1024772684219',
    projectId: 'community-56642',
    storageBucket: 'community-56642.appspot.com',
    iosClientId: '1024772684219-mt1eogdldj6m0v54m5tchgp6ec998r6s.apps.googleusercontent.com',
    iosBundleId: 'com.example.publicapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZBGyfumJ-qTbyiJ1R0r9Tl38nfdEX8ww',
    appId: '1:1024772684219:ios:1258d139ba770637386c9e',
    messagingSenderId: '1024772684219',
    projectId: 'community-56642',
    storageBucket: 'community-56642.appspot.com',
    iosClientId: '1024772684219-mt1eogdldj6m0v54m5tchgp6ec998r6s.apps.googleusercontent.com',
    iosBundleId: 'com.example.publicapp',
  );
}
